### ISSUE TITLE
No rule to make dt.img

### ISSUE THREAD

**Issue by EyeCantCU** [AOSParadox/android_device_oneplus_onyx#3]
When compiling AOSParadox, I am getting this error:

make: **\* No rule to make target 'out/target/product/onyx/dt.img', needed by 'out/target/product/onyx/boot.img'.  Stop.

What I don't quite understand, and why I am having issues fixing it is this is handled by dtbtool and mkbootimg.mk thus this error shouldn't appear. I did notice however that auditing out the kernel section in AndroidBoard.mk did allow further compilation however this error appeared yet again. 

My guess is something is severely broken in mkbootimg.mk but I am not entirely sure yet. I will have to take a closer look.

**Comment by EyeCantCU** [comment]
Oh and I forgot to mention that AndroidBoard.mk is a part of the generic msm8974 device tree

**Comment by LionelColaso** [comment]
try reverting this commit and build it should fix the issue am not sure though
https://github.com/AOSParadox/android_device_qcom_common/commit/f19465ed286aa94e78342a447e7c7f898f3bad0a

**Comment by EyeCantCU** [comment]
@loveboylion This seems to have fixed it. I will create a pull request. Good find...

**Comment by EyeCantCU** [comment]
And now we wait...

**Comment by EyeCantCU** [comment]
This is only a temporary fix until after the kernel has been built.

**Comment by EyeCantCU** [comment]
A temporary solution for YU devices was to use a prebuilt dt.img. I am going to look into this

**Comment by h2o64** [comment]
We aren't using a pre-built one any more

**Comment by EyeCantCU** [comment]
@h2o64 Then I will have a closer look at the trees and try to figure out what's going wrong. I think the source of the issue is in this tree itself considering that has been working fine for every other tree...

**Comment by h2o64** [comment]
I know exactly what's wrong ^^ but don't take it so important ^^ it's alright

**Comment by SeekingSight** [comment]
This shouldn't be a problem anymore since everything was rebased on the AOSPA tree but I just want to confirm that it isn't before closing @h2o64

**Comment by h2o64** [comment]
@SeekingSight don't worry 😉

**Comment by bootslag** [comment]
Im facing a similar issue. Any fixes?
