### ISSUE TITLE
Some problems of new device tree

### ISSUE THREAD

**Issue by YumeMichi** [AOSParadox/android_device_oneplus_onyx#5]
I tried to take a build on new device tree but unfortunately the data service seems not work, I was using AOSPA's vendor tree because AOSParadox's vendor tree is not compatible to new device tree. And there are a lot of other problems such as camera not work....
Waiting for update!

Here is a test build: [AOSParadox-STABLE-20160723-onyx.zip](https://rom.ikke.moe/onyx/AOSParadox-STABLE-20160723-onyx.zip)

![](https://blog.ikke.moe/img/Screenshot_20160723-155515.png)
![](https://blog.ikke.moe/img/Screenshot_20160723-155533.png)
![](https://blog.ikke.moe/img/Screenshot_20160723-155552.png)

**Comment by h2o64** [comment]
I'm not yet done
